import type { TenantContext, Role } from '@/shared/kernel/tenant-context';
import { Membership } from '../domain/membership.entity';
import type { MembershipRepository } from '../domain/ports/membership.repository';

export interface SyncMembershipInput {
  /** UUID string for the membership record. Generated by caller if new. */
  id: string;
  academyId: string;
  clerkUserId: string;
  role: Role;
}

/**
 * SyncMembershipUseCase — idempotent upsert of a membership.
 *
 * Called by the Clerk webhook delivery layer for
 * `organizationMembership.created` and `organizationMembership.updated`
 * events. Upsert on (academy_id, clerk_user_id) ensures re-delivery is safe
 * and role always reflects the latest event payload.
 *
 * No role assertion here — the webhook identity is pre-verified by Svix
 * and the write is scoped to the webhook's own tenant via withTenant.
 */
export class SyncMembershipUseCase {
  constructor(private readonly membershipRepo: MembershipRepository) {}

  async execute(ctx: TenantContext, input: SyncMembershipInput): Promise<void> {
    const now = new Date();
    const membership = new Membership({
      id: input.id,
      academyId: input.academyId,
      clerkUserId: input.clerkUserId,
      role: input.role,
      createdAt: now,
      updatedAt: now,
    });

    await this.membershipRepo.upsert(ctx, membership);
  }
}
